### ISSUE TITLE
_app.tsx 내부 Script 태그 이슈

### ISSUE THREAD

**Issue by hyeongrok7874** [themoment-team/HiRecruit-front#106]
## issue

`_app.tsx`의 Script 태그에서 발생하고 있는 이슈입니다!

`strategy="beforeInteractive"` beforeInteractive 옵션을 사용하려면 
`_document.tsx` 내부에서 사용해달라는 뜻 같습니다!

<img width="300" alt="스크린샷 2023-01-13 오후 3 57 43" src="https://user-images.githubusercontent.com/80103328/212258981-32b76168-bfac-4ae2-aa7d-6c0f9995ce29.png">

## Ref.

https://nextjs.org/docs/messages/no-before-interactive-script-outside-document

**Comment by sunwoo0706** [comment]
왜 `_app.tsx` 파일에 작성했을까요..
이슈 확인 감사드립니다.

ref. https://react-kakao-maps-sdk.jaeseokim.dev/docs/setup/next
