### ISSUE TITLE
Font optimization

### ISSUE THREAD

**Issue by hyeongrok7874** [themoment-team/HiRecruit-front#107]
## suggestion

Oct 9, 2022에 [release](https://github.com/orioncactus/pretendard/releases/tag/v1.3.6) 된 Pretendard의 가변 다이나믹 서브셋 적용을 해보는게 어떨까요?

현재의 방식보다 더 적은 용량으로 글꼴을 사용할 수 있게됩니다!

- 현재

<img width="300" alt="스크린샷 2023-01-13 오후 4 49 35" src="https://user-images.githubusercontent.com/80103328/212275874-b60bedb3-a6ff-4e8b-8552-01f7e56b001e.png">

- 개선 후

<img width="300" alt="스크린샷 2023-01-13 오후 4 56 08" src="https://user-images.githubusercontent.com/80103328/212275962-d6657649-7945-4dde-ad24-39cea1181336.png">

## Ref.

[가변 다이나믹 서브셋](https://github.com/orioncactus/pretendard#%EA%B0%80%EB%B3%80-%EB%8B%A4%EC%9D%B4%EB%82%98%EB%AF%B9-%EC%84%9C%EB%B8%8C%EC%85%8B)

**Comment by sunwoo0706** [comment]
늦게 답변드려 죄송합니다
좋아보이네요 ! 작업해주시면 확인해보겠습니다

**Comment by hyeongrok7874** [comment]
> 늦게 답변드려 죄송합니다 좋아보이네요 ! 작업해주시면 확인해보겠습니다

네 알겠습니다! 확인 감사합니다!
